# Generated by Django 4.2.6 on 2023-10-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
