# Generated by Django 4.2.6 on 2023-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
